[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "/opt/homebrew/bin/zellij attach -c"]

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Left", mods = "Command", chars = "\u001bb" },
  { key = "Right", mods = "Command", chars = "\u001bf" },
  { key = "Back", mods = "Command", chars = "\u001b\u007f" },
]

[terminal]
